# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "A fast and flexible text expander"
  homepage "https://github.com/noble-varghese/scribe"
  version "0.1.22"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/noble-varghese/scribe/releases/download/v0.1.22/scribe_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cfd6bde23fc07ae4063d1229f02a09c0067e56f312e3cde4a48d71a8f7a1d162"

      def install
        bin.install "scribe"
      end
    end
  end

  test do
    system "#{bin}/scribe", "--version"
  end
end
