# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "A fast and flexible text expander"
  homepage "https://github.com/noble-varghese/scribe"
  version "0.1.28"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/noble-varghese/scribe/releases/download/v0.1.28/scribe_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
    sha256 "7204c77b99c3eafb50a0d5a0585aa4079d738ae58a87a0d7d2aff7317c7f9a7c"

    def install
      bin.install "scribe"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/noble-varghese/scribe/releases/download/v0.1.28/scribe_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
    sha256 "b305bb264f351bdbee703a822fc4a2a8c83abd196b99d6097f166ed5e86860b1"

    def install
      bin.install "scribe"
    end
  end

  test do
    system "#{bin}/scribe", "--version"
  end
end
